import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';

export default function Home() {
  return (
    <> 
    <Head>
    <title>Jean-Marc Gagnebien Portfolio</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
    <section className='min-h-screen'>
    <h1>développeur</h1>
    <ul>
      <li>
        <BsFillMoonStarsFill />
      </li>
      <li>
        <a href='#'>Resume</a>
      </li>
    </ul>
    </section>
    </main>
    </>
    )
  }
  